# Generated by Django 3.2.13 on 2022-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220729_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='images/accounts/default_user_image.jpg', upload_to='images/accounts/'),
        ),
    ]
