# Generated by Django 3.2.13 on 2022-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/blog/default_post_image.jpg', upload_to='images/blog/%Y/%m/%d/'),
        ),
    ]
