# Generated by Django 3.2.13 on 2022-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Section Title')),
                ('header_description', models.TextField(blank=True, null=True, verbose_name='Header Section Description')),
                ('header_section_url', models.URLField(verbose_name='Header Button Url')),
                ('tut1_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tutorial 1 Title')),
                ('tut1_description', models.TextField(blank=True, null=True, verbose_name='Tutorial 1 Description')),
                ('tut1_url', models.URLField(verbose_name='Tutorial 1 Url')),
                ('tut2_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tutorial 2 Title')),
                ('tut2_description', models.TextField(blank=True, null=True, verbose_name='Tutorial 2 Description')),
                ('tut2_url', models.URLField(blank=True, null=True, verbose_name='Tutorial 2 Url')),
                ('middle_section_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Section Title')),
                ('middle_section_description', models.TextField(blank=True, null=True, verbose_name='Middle Section Description')),
                ('middle_section_img', models.ImageField(upload_to='images/')),
                ('tut3_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tutorial 3 Title')),
                ('tut3_description', models.TextField(blank=True, null=True, verbose_name='Tutorial 3 Description')),
                ('tut3_url', models.URLField(blank=True, null=True, verbose_name='Tutorial 3 Url')),
                ('tut4_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tutorial 4 Title')),
                ('tut4_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Tutorial 4 Description')),
                ('tut4_url', models.URLField(blank=True, null=True, verbose_name='Tutorial 4 Url')),
                ('social_sec_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Section Title')),
                ('social_sec_description', models.TextField(blank=True, null=True, verbose_name='Social Section Description')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram Url')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter Url')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Github Url')),
            ],
        ),
    ]
