# Generated by Django 3.2.13 on 2022-07-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220712_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='header_section_url',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tut1_url',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tut2_url',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tut3_url',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tut4_url',
        ),
    ]
